title: space-theme
description: "A modern, minimal space theme built for creating blazing-fast static websites using Jekyll"
encoding: utf-8

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]